"use client";

import React, { useState } from "react";
import { CacheProvider } from "@emotion/react";
import type { EmotionCache } from "@emotion/cache";
import createEmotionCache from "./createEmotionCache";
import { useServerInsertedHTML } from "next/navigation";

type Props = {
  children: React.ReactNode;
};

export default function EmotionRegistry({ children }: Props) {
  const [cache] = useState<EmotionCache>(() => createEmotionCache());

  useServerInsertedHTML(() => {
    // Collect any Emotion styles rendered during this server render and
    // insert them into the document head to avoid hydration mismatches.
    // `cache.sheet.tags` contains the style tags generated by Emotion.
    // We join their textContent and flush to avoid double-injection.
    const sheet = cache.sheet as
      | {
          tags?: Array<{ textContent?: string | null; key?: string }>;
          flush?: () => void;
        }
      | undefined;

    if (!sheet || !sheet.tags || sheet.tags.length === 0) return null;

    const css = sheet.tags.map((t) => t.textContent).join("");
    const names = sheet.tags.map((t) => t.key).join(" ");

    // flush so a second render won't duplicate styles
    if (typeof sheet.flush === "function") sheet.flush();

    return (
      <style data-emotion={`${cache.key} ${names}`} dangerouslySetInnerHTML={{ __html: css }} />
    );
  });

  return <CacheProvider value={cache}>{children}</CacheProvider>;
}
